### ISSUE TITLE
Undefined method password

### ISSUE THREAD

**Issue by paul-mesnilgrente** [rsolr/rsolr#243]
This created a bug in my project, it says `undefined method `password' for nil:NilClass` on `rsolr-2.6.0/lib/rsolr/error.rb:9:in `clean_uri'`

This bug has been introduced in https://github.com/rsolr/rsolr/pull/236/files merged in for version 2.6.0.

Or maybe I have a wrong setup and URI shouldn't be nil?

**Comment by jcoyne** [comment]
I'm wondering how it would work if you don't specify a URI.   Does it work in earlier versions?  Can you share how I might reproduce this error?

**Comment by paul-mesnilgrente** [comment]
It looks to be a sunspot bug, I'm running version 2.4.0 and it breaks. I'll update it when I can. The newer versions of it changed some behaviors that don't work for me.

**Comment by Antsiscool** [comment]
@paul-mesnilgrente I am seeing the same error when attempting to upgrade rsolr. I am running the latest version of sunspot (2.7.1).

Did upgrading sunspot fix the issue for you?
